package com.exertframework.RestAPIClient

interface Constant {
    companion object {
        const val BASE_URL = "http://192.168.254.41:5000/"
        const val IMAGE_BASE_URL = "http://192.168.254.41:5000/"
        const val CURRENCY = "QAR"

        const val LOGIN = "login"
        const val GET_ALL_CATEGORY = "getAllCategories"
        const val GET_SLIDER = "getSlider"
        const val GET_PRODUCTS_BY_ID = "getProductsById"
        const val FILTER_PRODUCT = "filterProducts"
        const val GET_WISHLIST = "getWishlist"
        const val GET_SORTBIES = "getSortbies"
        const val GET_PRODUCT_BY_ID = "getProductById"
        const val ADD_WISH_LIST_ITEM = "addWishlistItem"
        const val ADD_CART_ITEM = "addCartItem"
        const val GET_CART_ITEM = "getCartItems"
        const val DELETE_CART_ITEM = "deleteCartItem"
        const val GET_CART = "getCart"
        const val CHECK_OUT = "checkOut"
        const val UPDATE_CART = "updateCart"
        const val CLEAN_CART = "cleanCart"
        const val ORDER_ALERTS = "orderAlerts"
        const val GET_ORDER = "getOrder"
        const val UPDATE_ORDER = "updateOrder"
        const val ADD_ITEM_ORDER = "addItemOrder"
        const val ORDER_STATUS = "orderStatus"
        const val GET_MY_ORDER_DETAIL = "getMyOrderDetails"
        const val ORDER_LIST = "ordersList"
        const val GET_DISPATCH_ORDER = "getDispatchOrder"
        const val GET_REFUND_ORDER = "getRefundOrder"
        const val REFUND_COMPLETE_ORDER = "refundCompleteOrder"
        const val REFUND_ORDER_ITEMS = "refundOrderItems"
        const val DELETE_ITEM_ORDER = "deleteItemOrder"
        const val SEARCHING_ORDER = "seachingOrder"
        const val SEARCHED_ORDERS = "searchedOrders"
        const val ORDER_REPORT = "orderReport"
        const val GET_ALL_BRAND = "getAllBrands"
        const val INVENTORY_REPORT = "inventoryReport"
        const val UPDATE_USER = "updateUser"
        const val DISCARD_ORDER = "discardOrder"
        const val SAVE_ORDER = "saveOrder"
        const val DISPATCHED_ORDER = "dispatchedOrder"
        const val GENERATE_RECEVING_NOTE = "generate_receiving_note"
        const val DROP_RECEIPT = "dropReceipt"
        const val ORDER_RECEIPT = "orderReceipt"
        const val UPLOAD_RECEIPTS = "uploadReceipts"
        const val FORGOT = "forgot"
        const val LOGOUT = "logout"
        const val DELETE_CART_PRODUCT = "deleteCartProduct"
        const val DELETE_WISHLIST_ITEM = "deleteWishlistItem"
        const val HELP = "getHelp"
        const val DIARIZATION = "app"

    }
}